### ISSUE TITLE
Doubled Characters on opening MAN Pages

### ISSUE THREAD

**Issue by konqui** [l7ssha/manvs#1]
Hey there i like your extension a lot. I always wanna have the possibility to quickly open man pages inside of vscode since i use vscode a lot for Shell scripting.

But as you can see in the Screenshot at the Buttom it opens the MAN Pages with doubled Characters.
I already know this Problem from Textmate which i used before VS Code came out for Mac. 

I have taken a look into the the locally installed manvs extension on my VS Code and saw that you basically just call and grab the output of `man ${cmd}` so the simplest fix may be to use `man ${cmd} | col -b` instead.

I already changed it on my local copy and it works as expected. But i also wanna give you the little hint. Since it may help you and others who like these extension.

---

If you don't know `col` here is the interesting part from it's MAN Page:

    NAME
        col -- filter reverse line feeds from input

    SYNOPSIS
        col [-bfhpx] [-l num]

    DESCRIPTION
        The col utility filters out reverse (and half reverse) line feeds so that the output
        is in the correct order with only forward and half forward line feeds, and replaces
        white-space characters with tabs where possible.  This can be useful in processing
        the output of nroff(1) and tbl(1).

        The col utility reads from the standard input and writes to the standard output.

        The options are as follows:

        -b      Do not output any backspaces, printing only the last character written to
                each column position.

---

<img width="733" alt="printscreen_20141208_125422 2018-04-19 um 10 00 01" src="https://user-images.githubusercontent.com/782442/38978782-a1bf29b2-43b8-11e8-9df8-cb220f920888.png">

**Comment by l7ssha** [comment]
Thank's for that. I'll check this today and push fix
